import time
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index")
driver.maximize_window()
time.sleep(5)
uname = driver.find_element(By.XPATH,"//input[@name='username']")
uname.send_keys("Admin")
passwd = driver.find_element(By.XPATH, "//input[@name='password']")
passwd.send_keys("admin123")
time.sleep(5)
# Click log in button to login the website.
login = driver.find_element(By.XPATH,"//button[@class='oxd-button oxd-button--medium oxd-button--main orangehrm-login-button']")
login.click()
time.sleep(3)
print("The user is logged in successfully")

# # Test case ID: TC_PIM_01
Admin = driver.find_element(By.XPATH,"//span[@class='oxd-text oxd-text--span oxd-main-menu-item--name']")
Admin.click()
time.sleep(5)
print("Admin page is Displayed with other Menu options with Search(Text Box) on Admin Homepage")
Search_textbox = driver.find_element(By.XPATH,"//input[@class='oxd-input oxd-input--active' and @placeholder='Search']")
Search_textbox.click()
print(Search_textbox.is_displayed())
# Search all Menu's
Search_textbox.send_keys("admin")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("ADMIN")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("pim")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("PIM")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("leave")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("LEAVE")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("time")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("TIME")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("recruitment")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("RECRUITMENT")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("MY INFO")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("my info")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("performance")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("PERFORMANCE")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("dashboard")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("DASHBOARD")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("directory")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("DIRECTORY")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("maintenance")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("MAINTENANCE")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("buzz")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)
Search_textbox.send_keys("BUZZ")
time.sleep(4)
Search_textbox.send_keys(Keys.CONTROL, "a")
Search_textbox.send_keys(Keys.DELETE)
time.sleep(3)

# # 2. Validation of Page Headers-Dropdown on Admin Page
Admin = driver.find_element(By.XPATH,"//span[@class='oxd-text oxd-text--span oxd-main-menu-item--name']")
Admin.click()
time.sleep(5)
print("Admin page is Displayed with other Menu options with Search(Text Box) on Admin Homepage")
user_management = driver.find_element(By.XPATH, "//span[contains(text(),'User Management')]").click()
time.sleep(3)
user = driver.find_element(By.LINK_TEXT,"Users").click()
time.sleep(3)
user_role = driver.find_element(By.XPATH, "/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[2]/div/div[2]/div/div/div[2]/i")
user_role.click()
print("User role displayed:",user_role.is_displayed())
time.sleep(5)
status = driver.find_element(By.XPATH, "/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[4]/div/div[2]/div/div/div[2]/i")
status.click()
time.sleep(3)
print("System displayed:",status.is_displayed())
time.sleep(5)

# 3. Creation of New Employee under PIM
Admin = driver.find_element(By.XPATH,"//span[@class='oxd-text oxd-text--span oxd-main-menu-item--name']")
Admin.click()
time.sleep(5)
print("Admin page is Displayed with other Menu options with Search(Text Box) on Admin Homepage")
PIM = driver.find_element(By.XPATH,"//a[contains(@href,'/web/index.php/pim/viewPimModule')]")
PIM.click()
time.sleep(5)
addEmp = driver.find_element(By.XPATH,"//button[@class='oxd-button oxd-button--medium oxd-button--secondary']")
addEmp.click()
time.sleep(5)
firstName = driver.find_element(By.XPATH,"//input[@name='firstName']").send_keys("Anjali")
lastName = driver.find_element(By.XPATH,"//input[@name='lastName']").send_keys("Kaira")
time.sleep(2)
toggle = driver.find_element(By.XPATH,"//span[@class='oxd-switch-input oxd-switch-input--active --label-right']").click()
user_name = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[3]/div/div[1]/div/div[2]/input")
user_name.send_keys("Anjalikz")
enabled = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[3]/div/div[2]/div/div[2]/div[1]/div[2]/div/label/span")
enabled.click()
time.sleep(3)
password = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[4]/div/div[1]/div/div[2]/input")
password.send_keys("$Atish81211819")
confirm_pass = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[4]/div/div[2]/div/div[2]/input")
confirm_pass.send_keys("$Atish81211819")
time.sleep(3)
save = driver.find_element(By.XPATH,"//button[@class='oxd-button oxd-button--medium oxd-button--secondary orangehrm-left-space']").click()
time.sleep(5)
print("Employee is added successfully")
time.sleep(5)

# 4. Validation of Employee Personal Details page post User Creation
time.sleep(5)
contact_details = driver.find_element(By.LINK_TEXT,"Contact Details")
contact_details.click()
#print(contact_details.is_selected())
time.sleep(3)
emergency_contacts = driver.find_element(By.LINK_TEXT,"Emergency Contacts")
emergency_contacts.click()
time.sleep(3)
#print(emergency_contacts.is_displayed())
dependants = driver.find_element(By.LINK_TEXT,"Dependents")
dependants.click()
time.sleep(3)
#print(dependants.is_displayed())
Immigration = driver.find_element(By.LINK_TEXT,"Immigration")
Immigration.click()
time.sleep(3)
#print(Immigration.is_displayed())
Job = driver.find_element(By.LINK_TEXT,"Job")
Job.click()
time.sleep(3)
#print(Job.is_displayed())
Salary = driver.find_element(By.LINK_TEXT,"Salary")
Salary.click()
time.sleep(3)
#print(Salary.is_displayed())
Tax_exemption = driver.find_element(By.LINK_TEXT,"Tax Exemptions")
Tax_exemption.click()
time.sleep(3)
#print(Tax_exemption.is_displayed())
Report_to = driver.find_element(By.LINK_TEXT,"Report-to")
Report_to.click()
time.sleep(3)
#print(Report_to.is_displayed())
qualification = driver.find_element(By.LINK_TEXT,"Qualifications")
qualification.click()
time.sleep(3)
#print(qualification.is_displayed())
memberships = driver.find_element(By.LINK_TEXT,"Memberships")
memberships.click()
time.sleep(3)

#5.Updating Employee Personal Details page post User Creation

personal_details = driver.find_element(By.LINK_TEXT,"Personal Details").click()
time.sleep(5)
nickname = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div[2]/div/div/div[2]/input")
nickname.send_keys("Sat")
time.sleep(3)
other_Id = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[1]/div[2]/div/div[2]/input")
other_Id.send_keys("123456")
time.sleep(3)
driving_liscense = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[2]/div[1]/div/div[2]/input")
driving_liscense.send_keys("573893343")
time.sleep(3)
liscense_expdate = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[2]/div[2]/div/div[2]/div/div/input")
liscense_expdate.send_keys("2023-03-09")
time.sleep(3)
gender = driver.find_element(By.XPATH,"//label[text()='Female']")
gender.click()
military_service = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/div/div[1]/div/div[2]/input")
military_service.send_keys("Service one")
time.sleep(3)
save_personal = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]/button").click()
time.sleep(2)
save_blood_type = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/form/div[2]/button").click()
file_upload = driver.find_element(By.XPATH,"//button[@class='oxd-button oxd-button--medium oxd-button--text']").click()

#6.Updating Employee Contact Details page post User Creation.py
contact_details = driver.find_element(By.LINK_TEXT,"Contact Details").click()
driver.implicitly_wait(3)
street1 = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input")
street1.send_keys("Bank street")
street2 = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/input")
street2.send_keys("Ab nagar street")
city = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[3]/div/div[2]/input")
city.send_keys("Hyderabad")
state = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[4]/div/div[2]/input")
state.send_keys("Hyd")
Zip_postalcode = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[5]/div/div[2]/input")
Zip_postalcode.send_keys("503943")
time.sleep(3)
country = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[6]/div/div[2]/div/div/div[2]/i")
country.click()
country_name = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[6]/div/div[2]/div/div/div[1]")
country_name.click()
home = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[1]/div/div[2]/input")
home.send_keys("040-928423")
mobile = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[2]/div/div[2]/input")
mobile.send_keys("8121883992")
time.sleep(3)
work = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[3]/div/div[2]/input")
work.send_keys("0504565")
work_mail = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/div[1]/div/div[2]/input")
work_mail.send_keys("anjali@gmail.com")
other_mail = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/div[2]/div/div[2]/input")
other_mail.send_keys("anjali123@gmail.com")
save_contacts = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/button")
save_contacts.click()
billable = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/form/div[1]/div/div/div/div[2]/div/div/div[2]/i")
billable.click()
billable_type = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/form/div[1]/div/div/div/div[2]/div/div/div[1]")
billable_type.click()
save_custom = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/form/div[2]/button")
save_custom.click()

# 7.Emergency contacts
emergency_contacts = driver.find_element(By.LINK_TEXT,"Emergency Contacts")
emergency_contacts.click()
driver.implicitly_wait(5)
Add_ec = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/div/button").click()
Name = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input").send_keys("satish")
relation = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/input").send_keys("Cousin")
home_telephone = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[1]/div/div[2]/input").send_keys("8687364")
mobile1 = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[2]/div/div[2]/input").send_keys("9876543456")
work_telephone = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[2]/div/div[2]/input").send_keys("040-983772")
save_ec = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/button[2]").click()

# 8.contact details:
driver.implicitly_wait(5)
dependants = driver.find_element(By.LINK_TEXT,"Dependents")
dependants.click()
driver.implicitly_wait(10)
Add_dep = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/div/button").click()
Name_dep = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input").send_keys("Ramesh")
Relation = driver.find_element(By.XPATH,"//i[@class='oxd-icon bi-caret-down-fill oxd-select-text--arrow']")
Relation.click()
Relation_type = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/div/div/div[1]").send_keys("Child")
dob_relation = driver.find_element(By.XPATH,"//i[@class='oxd-icon bi-calendar oxd-date-input-icon']").click()
dob_relation_date = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div/div/div[2]/div/div/input").send_keys("1970-01-01")
save_dep = driver.find_element(By.XPATH,"//button[@class='oxd-button oxd-button--medium oxd-button--secondary orangehrm-left-space']").click()

# 9. Update Job details
Job = driver.find_element(By.LINK_TEXT,"Job").click()
driver.implicitly_wait(10)
joined_date = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/div/div/input").send_keys("2023-01-03")
job_title = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/div/div/div[1]").send_keys("QA Engineer")
job_category = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[4]/div/div[2]/div/div/div[1]").send_keys("Professionals")
sub_unit = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[5]/div/div[2]/div/div/div[1]").send_keys("Quality Assurance")
location = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[6]/div/div[2]/div/div/div[1]").send_keys("New York Sales Office")
emploment_status = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[7]/div/div[2]/div/div/div[1]").send_keys("Full-Time Permanent")
time.sleep(4)
#include_details = driver.find_element(By.XPATH,"//span[@class='oxd-switch-input oxd-switch-input--active --label-right']").click()
# toggle_include = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/label/input").click()
# time.sleep(8)
# contract_startdate = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/div[1]/div/div[2]/div/div/input")
# contract_startdate.send_keys("2023-01-01")
# contract_enddate = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/div[2]/div/div[2]/div/div/input")
# contract_enddate.send_keys("2025-01-01")
save_job = driver.find_element(By.XPATH,"//button[@class='oxd-button oxd-button--medium oxd-button--secondary orangehrm-left-space']").click()


# 10. Terminate Employee
time.sleep(5)
terminate_emp = driver.find_element(By.XPATH,"//button[@class='oxd-button oxd-button--medium oxd-button--label-danger --termination-button']").click()
termi_date = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[1]/div/div[2]/div/div/input")
termi_date.send_keys("2023-05-06")
termi_reason = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[2]/div/div[2]/div/div/div[1]")
termi_reason.send_keys("Laid-off")
note = driver.find_element(By.XPATH,"//textarea[@class='oxd-textarea oxd-textarea--active oxd-textarea--resize-vertical']").send_keys("Pls note that you are laid-off")
save_termi = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[4]/button[2]").click()
time.sleep(5)
print("Employee terminated")

# 11. Activate Employee
time.sleep(5)
job_page = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[6]/a").click()
driver.implicitly_wait(4)
activate_emp = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/button").click()

# 12. Update Salary Details
Salary = driver.find_element(By.LINK_TEXT,"Salary").click()
driver.implicitly_wait(10)
addsalary = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/div/button").click()
sal_comp = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input").send_keys("Basic")
pay_grade = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/div/div/div[1]").send_keys("Grade 1")
pay_frequency = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[3]/div/div[2]/div/div/div[1]").send_keys("Monthly")
currecy = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[4]/div/div[2]/div/div/div[1]").send_keys("United States Dollar")
amount = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[5]/div/div[2]/input").send_keys("72000")
comments = driver.find_element(By.XPATH,"//textarea[@class='oxd-textarea oxd-textarea--active oxd-textarea--resize-vertical']").send_keys("All good")
save_sal = driver.find_element(By.XPATH,"//button[@class='oxd-button oxd-button--medium oxd-button--secondary orangehrm-left-space']").click()
time.sleep(5)

# 13. Update emp salary on tax Exemptions page
Tax_exemption = driver.find_element(By.LINK_TEXT,"Tax Exemptions")
driver.implicitly_wait(10)
Inc_status = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/div/div/div[1]").send_keys("Single")
exemptions = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/input").send_keys("12")
state = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/div/div/div[1]").send_keys("Arizona")
state_status = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[2]/div/div[2]/div/div/div[1]").send_keys("Married")
Unemp_state = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[4]/div/div[2]/div/div/div[1]").send_keys("Arizona")
work_status = driver.find_element(By.XPATH,"/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[5]/div/div[2]/div/div/div[1]").send_keys("Alaska")
save_tax = driver.find_element(By.XPATH,"//button[@class='oxd-button oxd-button--medium oxd-button--secondary orangehrm-left-space']").click()
